# Generated by Django 4.2.7 on 2023-11-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Математика, перебор, графы ...', max_length=150, unique=True, verbose_name='Наименование темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.PositiveIntegerField(blank=True, help_text='1, 2, 3, ...', null=True, verbose_name='id Конкурсной задачи')),
                ('contest_index', models.CharField(help_text='A, B, C, ...', max_length=10, verbose_name='index Конкурсной задачи')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование задачи')),
                ('type', models.CharField(help_text='PROGRAMMING, QUESTION, ...', max_length=150, verbose_name='Тип задачи')),
                ('points', models.PositiveIntegerField(blank=True, help_text='Максимальное количество баллов за задачу', null=True, verbose_name='Количество баллов')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Рейтинг задачи (сложность)', null=True, verbose_name='Рейтинг')),
                ('solved_count', models.PositiveIntegerField(default=0, help_text='Количество людей, решивших задачу', verbose_name='Количество решений')),
                ('category', models.ManyToManyField(help_text='Теги задачи', to='diploma_task_parser.topic', verbose_name='Темы задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('solved_count',),
                'unique_together': {('contest_id', 'contest_index')},
            },
        ),
    ]
